sudo: false

language: node_js

cache:
  directories:
    - node_modules

node_js:
 - 0.10
 - 0.12
 - 4
 - 5

before_install:
  - npm i -g npm@^2.0.0

before_script:
  - npm prune

after_success:
  - curl -Lo travis_after_all.py https://git.io/travis_after_all
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
